name: mvmnt_cli
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  equatable: ^2.0.7
  crypto: ^3.0.3
  uuid: ^4.5.1
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  logger: ^2.5.0
  socket_io_client: ^3.1.2
  get_it: ^8.0.3
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.6
  flutter_bloc: ^9.1.0
  go_router: ^15.0.0
  connectivity_plus: ^6.1.4
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.1
  app_tracking_transparency: ^2.0.6+1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_messaging: ^15.2.5
  firebase_crashlytics: ^4.3.5
  firebase_analytics: ^11.4.5
  firebase_remote_config: ^5.4.4
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  flutter_facebook_auth: ^7.1.2
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  geolocator: ^14.0.0
  geocoding: ^4.0.0
  google_maps_flutter: ^2.12.2
  sliding_up_panel2: ^3.3.0+1
  shimmer: ^3.0.0
  flutter_svg: ^2.1.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  flutter_stripe: ^11.5.0
  pay: ^3.2.1
  webview_flutter: ^4.9.0
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  flutter_typing_indicator: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer:
  flutter_lints:
  build_runner:
  hive_generator:
  mockito:
  bloc_test:

flutter:
  generate: true

  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/map/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Black.ttf
        - asset: assets/fonts/Lexend-Bold.ttf
        - asset: assets/fonts/Lexend-ExtraBold.ttf
        - asset: assets/fonts/Lexend-ExtraLight.ttf
        - asset: assets/fonts/Lexend-Light.ttf
        - asset: assets/fonts/Lexend-Medium.ttf
        - asset: assets/fonts/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend-SemiBold.ttf
        - asset: assets/fonts/Lexend-Thin.ttf
