name: auth
description: Authentication Kit package
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.6.2
  flutter_facebook_auth: ^7.1.2
  google_sign_in: ^7.1.0
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.6
  uuid: ^4.5.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
