name: muvmnt_core
description: Core Kit package
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  pretty_dio_logger: ^1.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
  
