// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions are not supported for this platform.',
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZw7Jr8sgQqZmrcNPWeJiPBBtVpwQ596Q',
    appId: '1:998122439825:android:3fa5351e05273cce47ab30',
    messagingSenderId: '998122439825',
    projectId: 'mvmnt-cli',
    storageBucket: 'mvmnt-cli.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl0J1jlzg7_UIeweEaEPBotLnlNLwEpfE',
    appId: '1:998122439825:ios:a4b51a7a69f8c3a247ab30',
    messagingSenderId: '998122439825',
    projectId: 'mvmnt-cli',
    storageBucket: 'mvmnt-cli.firebasestorage.app',
    iosClientId: '998122439825-mho30s83pgn9d0i8g1827up5lbbrejk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mvmntCli',
  );

}